cc_binary(
    name = "ipc_receive",
    srcs = ["ipc_receive.cpp"],
    deps = ["//lib:ipc-handler"],
)

cc_binary(
    name = "ipc_send",
    srcs = ["ipc_send.cpp"],
    deps = ["//lib:ipc-handler"],
)
